/**
 * Crimes that are not car theft. DESIGN_v12.md §4.
 *
 * Each one is another SegmentRun configuration — the same engine that drives
 * the four-stage heist, fed different segments, options and state vars. That
 * was the whole point of surgery S1: adding a kind of crime is a content
 * change, not an engine change.
 *
 * `take` accumulates during the run, so how the job went decides what it was
 * worth. Grabbing more means staying longer, and staying longer is what gets
 * you caught.
 */

import type { SegmentRunConfig } from './types.js'

export type CrimeKey = 'pickpocket' | 'atm' | 'burgle' | 'holdup'

const VARS = {
  noise: { init: 0, min: 0, max: 100, label: '动静' },
  time: { init: 0, min: 0, max: 60, label: '耗时' },
  take: { init: 0, min: 0, max: 100_000, label: '到手' },
} as const

const BLOWN = [{ var: 'noise', atLeast: 100, text: '有人在喊。整条街都朝这边看。' }]

export const CRIME_CONFIGS: Record<CrimeKey, SegmentRunConfig> = {
  // ── 扒窃：本钱最小的活，也是唯一一件失手了还能笑着走开的 ──────────
  pickpocket: {
    id: 'pickpocket',
    title: '扒窃',
    vars: VARS,
    failWhen: BLOWN,
    segments: [
      {
        id: 'mark',
        title: '挑人',
        intro: '取款机前面排着七八个人。你站在报刊亭的阴影里看了两分钟。',
        tell: {
          accurate: '第三个，左后袋，钱包鼓得把裤线撑歪了。他一直在看手机。',
          vague: '人来人往。谁身上有东西，你只能猜。',
          misleading: '排头那个穿西装的，手一直按着胸口的位置——那儿准有东西。',
          nerveHint: '……按着胸口的人，通常是因为他知道那儿有东西。',
        },
        abortHeat: 0,
        abortText: '你从人群边上走开了。今天不合适。',
        options: [
          {
            id: 'distracted',
            label: '等一个走神的',
            hint: '最稳，但要耗时间',
            skill: 'stealth',
            defense: 'exposure',
            modifier: 0.12,
            onSuccess: [{ var: 'time', amount: 3 }],
            onFailure: [
              { var: 'time', amount: 3 },
              { var: 'noise', amount: 10 },
            ],
            successText: '他终于低头去看手机了。整个人像不在这条街上。',
            failureText: '你等得太久，取款机旁边那个保安开始注意你。',
          },
          {
            id: 'crowd',
            label: '挤进最密的地方',
            hint: '掩护好，但你也看不清',
            skill: 'stealth',
            defense: 'exposure',
            modifier: 0.05,
            onSuccess: [{ var: 'time', amount: 1 }],
            onFailure: [{ var: 'noise', amount: 14 }],
            successText: '肩碰肩的地方最安全。谁都不会记得谁碰过谁。',
            failureText: '有人被你挤得回头看了一眼，眼神停得有点久。',
          },
          {
            id: 'rich',
            label: '挑个看着有钱的',
            hint: '油水多，但这种人警觉',
            skill: 'nerve',
            defense: 'exposure',
            modifier: -0.08,
            onSuccess: [
              { var: 'take', amount: 260 },
              { var: 'time', amount: 2 },
            ],
            onFailure: [{ var: 'noise', amount: 18 }],
            successText: '手表比车还贵。这种人身上从不只带一点。',
            failureText: '穿得起那身衣服的人，防得也比别人紧。他侧了侧身。',
          },
        ],
      },
      {
        id: 'lift',
        title: '下手',
        intro: '两步的距离。手从口袋里出来的时候不能是空的。',
        tell: {
          accurate: '钱包在左后袋，扣子没扣。三根手指的事。',
          vague: '你看不出他把东西放在哪一边。',
          misleading: '外套内袋，扣子松着——你听说这种人都放那儿。',
          nerveHint: '……这话是谁跟你说的来着。',
        },
        abortHeat: 4,
        abortText: '你的手停在半路上，然后收了回来。',
        options: [
          {
            id: 'pocket',
            label: '掏后袋',
            hint: '最直接',
            skill: 'stealth',
            defense: 'security',
            modifier: 0.06,
            onSuccess: [{ var: 'take', amount: 180 }],
            onFailure: [{ var: 'noise', amount: 30 }],
            successText: '出来了。轻得像抽一张纸。',
            failureText: '他猛地转身，一把攥住你的手腕。',
          },
          {
            id: 'bump',
            label: '撞他一下再道歉',
            hint: '老办法，动静大一点',
            skill: 'nerve',
            defense: 'security',
            modifier: 0.1,
            onSuccess: [
              { var: 'take', amount: 150 },
              { var: 'noise', amount: 8 },
            ],
            onFailure: [{ var: 'noise', amount: 26 }],
            successText: '"对不住啊。" 他摆摆手说没事，一边说一边走远了。',
            failureText: '"你他妈——" 他先低头摸了摸口袋，然后抬起头。',
          },
          {
            id: 'bag',
            label: '摸他的包',
            hint: '东西多，但要多花几秒',
            skill: 'stealth',
            defense: 'security',
            modifier: -0.05,
            onSuccess: [
              { var: 'take', amount: 340 },
              { var: 'time', amount: 2 },
            ],
            onFailure: [{ var: 'noise', amount: 24 }],
            successText: '拉链一路开到底都没出声。里面比你想的多。',
            failureText: '拉链卡住了。就那么一秒，他感觉到了背后的重量。',
          },
        ],
      },
    ],
  },

  // ── 撬 ATM：机器不会喊，但它会记着 ────────────────────────────────
  atm: {
    id: 'atm',
    title: '撬取款机',
    vars: VARS,
    failWhen: BLOWN,
    segments: [
      {
        id: 'watch',
        title: '踩点',
        intro: '这台机器嵌在墙里，正对着街。凌晨三点，街上只有一盏灯是亮的。',
        tell: {
          accurate: '摄像头在斜对面，角度只扫到取款人的背。运钞车周二来。',
          vague: '街上没人。你不知道有没有东西在看着。',
          misleading: '那个摄像头是坏的，坏了三个月了。整条街没人管。',
          nerveHint: '……坏了三个月的摄像头，通常早就换了。',
        },
        abortHeat: 0,
        abortText: '你从机器前面走过去，没有停。',
        options: [
          {
            id: 'patient',
            label: '在对面坐一会儿',
            hint: '摸清节奏，费时间',
            skill: 'stealth',
            defense: 'exposure',
            modifier: 0.12,
            onSuccess: [{ var: 'time', amount: 4 }],
            onFailure: [
              { var: 'time', amount: 4 },
              { var: 'noise', amount: 8 },
            ],
            successText: '四十分钟里过去两辆车。第二辆是巡逻的，慢得像在数门牌。',
            failureText: '你在同一个位置坐得太久。有人从窗帘后面看你。',
          },
          {
            id: 'quick',
            label: '走过去看一眼',
            hint: '快，但只看得到表面',
            skill: 'stealth',
            defense: 'exposure',
            modifier: 0,
            onSuccess: [{ var: 'time', amount: 1 }],
            onFailure: [{ var: 'noise', amount: 12 }],
            successText: '一眼够了。机器型号老得连键盘都磨平了。',
            failureText: '你放慢了脚步——在一条空街上，放慢脚步就是一件事。',
          },
          {
            id: 'scan',
            label: '用扫描器探一探',
            hint: '看得最清楚，但你不擅长这个',
            skill: 'electronic',
            defense: 'security',
            modifier: 0.05,
            onSuccess: [{ var: 'time', amount: 2 }],
            onFailure: [{ var: 'noise', amount: 10 }],
            successText: '屏幕上跳出一串你半懂不懂的东西。至少报警线路在哪你看明白了。',
            failureText: '设备一直在转圈。你不知道它在等什么。',
          },
        ],
      },
      {
        id: 'crack',
        title: '撬机',
        intro: '面板是钢的，锁孔在下沿。剩下的全是手上的事。',
        tell: {
          accurate: '老式机械锁，没有联网。撬开面板不会惊动任何人。',
          vague: '锁看不出年代。得摸进去才知道。',
          misleading: '就是个老机器，撬开面板它连叫都不会叫。',
          nerveHint: '……你自己其实没看清锁孔里有什么。',
        },
        abortHeat: 10,
        abortText: '你把工具收回包里。面板还是好的，你还站在外面。',
        options: [
          {
            id: 'pry',
            label: '撬面板',
            hint: '你的老本行',
            skill: 'mechanical',
            defense: 'security',
            modifier: 0.08,
            onSuccess: [
              { var: 'take', amount: 1400 },
              { var: 'time', amount: 3 },
              { var: 'noise', amount: 10 },
            ],
            onFailure: [{ var: 'noise', amount: 28 }],
            successText: '咔。钢板翘起来的时候带出一声闷响，然后就是钱。',
            failureText: '撬棍打滑，砸在钢板上。那一声在空街上传出去很远。',
            failureEndsRun: true,
          },
          {
            id: 'hack',
            label: '接线，让它自己吐',
            hint: '干净，但要电子',
            skill: 'electronic',
            defense: 'security',
            modifier: 0,
            onSuccess: [
              { var: 'take', amount: 1900 },
              { var: 'time', amount: 2 },
            ],
            onFailure: [{ var: 'noise', amount: 20 }],
            successText: '机器认了你接进去的那根线，开始一张一张地数。',
            failureText: '屏幕黑了一下，然后跳出一行红字。它认出了不对劲。',
            failureEndsRun: true,
          },
          {
            id: 'force',
            label: '整台撬下来',
            hint: '拿得最多，动静也最大',
            skill: 'mechanical',
            defense: 'security',
            modifier: 0.14,
            onSuccess: [
              { var: 'take', amount: 2400 },
              { var: 'noise', amount: 34 },
              { var: 'time', amount: 5 },
            ],
            onFailure: [{ var: 'noise', amount: 44 }],
            successText: '整台机器从墙里出来的时候，砖屑落了一地。',
            failureText: '墙比机器结实。你只把自己弄得满手是血。',
            failureEndsRun: true,
          },
        ],
      },
      {
        id: 'slip',
        title: '脱离',
        intro: '钱在包里。从现在开始，每一秒都在计价。',
        tell: {
          accurate: '往北那条小路能一直通到河边，中间没有路口。',
          vague: '两个方向都能走。你不知道哪边更糟。',
          misleading: '西头那条路刚修好，最顺。往那边走，两分钟出城。',
          nerveHint: '……"最顺"这个词，是别人替你选的。',
        },
        abortHeat: 16,
        abortText: '你把包塞进垃圾桶后面，空着手走开。',
        options: [
          {
            id: 'walk',
            label: '不跑，走',
            hint: '走的人不像贼',
            skill: 'nerve',
            defense: 'response',
            modifier: 0.1,
            onSuccess: [{ var: 'time', amount: 2 }],
            onFailure: [{ var: 'noise', amount: 12 }],
            successText: '你在路口等了整整一个红灯。没有人看你。',
            failureText: '你走得太慢了。慢到一辆巡逻车放慢了速度跟在后面。',
          },
          {
            id: 'run',
            label: '跑',
            hint: '快，但所有人都会记住',
            skill: 'driving',
            defense: 'response',
            modifier: 0,
            onSuccess: [{ var: 'noise', amount: 14 }],
            onFailure: [{ var: 'noise', amount: 28 }],
            successText: '三个街区，一次都没回头。',
            failureText: '你撞翻了路边的垃圾桶。整条街都醒了。',
          },
          {
            id: 'backstreets',
            label: '钻巷子',
            hint: '甩得掉，但要绕远',
            skill: 'stealth',
            defense: 'response',
            modifier: 0.08,
            onSuccess: [{ var: 'time', amount: 4 }],
            onFailure: [{ var: 'noise', amount: 20 }],
            successText: '第四个弯之后，身后什么声音都没有了。',
            failureText: '这条巷子是死的。你退出来的时候听见了警笛。',
          },
        ],
      },
    ],
  },

  // ── 入室：最费时间的活，也是唯一能翻出意外之物的 ──────────────────
  burgle: {
    id: 'burgle',
    title: '入室行窃',
    vars: VARS,
    failWhen: BLOWN,
    segments: [
      {
        id: 'case',
        title: '踩点',
        intro: '一整排一模一样的房子。你要挑的是那扇晚上不亮灯的。',
        tell: {
          accurate: '左起第三家，信箱塞满了，草坪三周没剪。人不在。',
          vague: '有几家看着是空的。看着而已。',
          misleading: '拐角那家肯定没人，窗帘拉了一个星期没动过。',
          nerveHint: '……窗帘一个星期没动，也可能是里面的人不想动。',
        },
        abortHeat: 0,
        abortText: '你顺着人行道走过去，像个下班回家的人。',
        options: [
          {
            id: 'mail',
            label: '看信箱和草坪',
            hint: '老办法，最准',
            skill: 'stealth',
            defense: 'exposure',
            modifier: 0.12,
            onSuccess: [{ var: 'time', amount: 3 }],
            onFailure: [{ var: 'noise', amount: 10 }],
            successText: '信箱塞不下了。草长到能没过脚踝。这家人走了不止三天。',
            failureText: '你在别人家信箱前站得太久。对门的窗帘动了一下。',
          },
          {
            id: 'knock',
            label: '上去敲门',
            hint: '最确定，但你的脸被记住了',
            skill: 'nerve',
            defense: 'exposure',
            modifier: 0.16,
            onSuccess: [
              { var: 'time', amount: 1 },
              { var: 'noise', amount: 6 },
            ],
            onFailure: [{ var: 'noise', amount: 22 }],
            successText: '敲了三遍，没人。你退开两步，看了看二楼——也没人。',
            failureText: '门开了。一个老太太隔着防盗链看着你。',
          },
          {
            id: 'back',
            label: '绕到后面看',
            hint: '不被街上看见，但看不到正面',
            skill: 'stealth',
            defense: 'exposure',
            modifier: 0.04,
            onSuccess: [{ var: 'time', amount: 2 }],
            onFailure: [{ var: 'noise', amount: 16 }],
            successText: '后院的门虚掩着。这家人连这个都懒得管。',
            failureText: '隔壁的狗先听见了你。',
          },
        ],
      },
      {
        id: 'enter',
        title: '进屋',
        intro: '后门，厨房窗，或者干脆走前门。三条路，三种代价。',
        tell: {
          accurate: '厨房那扇窗的插销是坏的。推一下就能开。',
          vague: '门窗看不出松紧。得试。',
          misleading: '后门那把锁是最老的那种，一撬就开。',
          nerveHint: '……你并没有真的看清那把锁。',
        },
        abortHeat: 12,
        abortText: '你把手从门把上拿开，转身走了。',
        options: [
          {
            id: 'window',
            label: '推厨房的窗',
            hint: '最安静',
            skill: 'stealth',
            defense: 'security',
            modifier: 0.06,
            onSuccess: [{ var: 'time', amount: 2 }],
            onFailure: [{ var: 'noise', amount: 24 }],
            successText: '窗框吱了一声，然后就开了。屋里是凉的。',
            failureText: '插销是新的。你推的时候整扇窗都在响。',
            failureEndsRun: true,
          },
          {
            id: 'lock',
            label: '撬后门的锁',
            hint: '你的老本行',
            skill: 'mechanical',
            defense: 'security',
            modifier: 0.08,
            onSuccess: [{ var: 'time', amount: 3 }],
            onFailure: [{ var: 'noise', amount: 26 }],
            successText: '咔。二十年了，这个声音一次都没变过。',
            failureText: '锁芯是换过的。你在门口蹲了十分钟，一无所获。',
            failureEndsRun: true,
          },
          {
            id: 'smash',
            label: '砸玻璃',
            hint: '一定进得去，一定有人听见',
            skill: 'nerve',
            defense: 'security',
            modifier: 0.3,
            onSuccess: [{ var: 'noise', amount: 38 }],
            onFailure: [{ var: 'noise', amount: 50 }],
            successText: '玻璃碎在地毯上，声音比你想的小。但也只是比你想的小。',
            failureText: '玻璃碎了，警报也响了。你没想到这种房子会装警报。',
            failureEndsRun: true,
          },
        ],
      },
      {
        id: 'ransack',
        title: '搜刮',
        intro: '屋里很安静，安静到你能听见自己的呼吸。你有多少时间，取决于你敢待多久。',
        tell: {
          accurate: '主卧的抽屉柜第二层，首饰盒就摆在明面上。',
          vague: '柜子很多。你不知道该先开哪一个。',
          misleading: '这种人家钱都放书房。书房准有个保险箱。',
          nerveHint: '……你从没进过这家的书房。',
        },
        abortHeat: 8,
        abortText: '你把手里的东西放回原处，从来路退了出去。',
        options: [
          {
            id: 'quick',
            label: '只拿明面上的',
            hint: '三分钟就走',
            skill: 'stealth',
            defense: 'response',
            modifier: 0.14,
            onSuccess: [
              { var: 'take', amount: 700 },
              { var: 'time', amount: 2 },
            ],
            onFailure: [{ var: 'noise', amount: 14 }],
            successText: '钱包、手表、抽屉里的现金。三分钟，出门。',
            failureText: '你碰倒了玄关的花瓶。',
          },
          {
            id: 'thorough',
            label: '一间一间翻',
            hint: '拿得多，但时间在走',
            skill: 'stealth',
            defense: 'response',
            modifier: -0.06,
            onSuccess: [
              { var: 'take', amount: 1800 },
              { var: 'time', amount: 6 },
              { var: 'noise', amount: 10 },
            ],
            onFailure: [
              { var: 'take', amount: 400 },
              { var: 'noise', amount: 30 },
            ],
            successText: '衣柜夹层里有一个信封。里面的厚度让你愣了一下。',
            failureText: '你在二楼听见楼下的门响了。',
          },
          {
            id: 'safe',
            label: '找保险箱',
            hint: '要么最多，要么白费',
            skill: 'mechanical',
            defense: 'security',
            modifier: -0.14,
            onSuccess: [
              { var: 'take', amount: 3200 },
              { var: 'time', amount: 8 },
              { var: 'noise', amount: 14 },
            ],
            onFailure: [
              { var: 'time', amount: 8 },
              { var: 'noise', amount: 26 },
            ],
            successText: '书房衣柜后面。三十年前的锁，对你来说不算锁。',
            failureText: '你把书房翻了个底朝天。这家人根本没有保险箱。',
          },
        ],
      },
    ],
  },

  // ── 持械抢劫：唯一一件会让人记住你的脸的活 ────────────────────────
  holdup: {
    id: 'holdup',
    title: '持械抢劫',
    vars: VARS,
    failWhen: BLOWN,
    segments: [
      {
        id: 'walkin',
        title: '进店',
        intro: '凌晨两点的加油站便利店。里面只有一个店员，正在看柜台下面的电视。',
        tell: {
          accurate: '就他一个人。后门没锁，摄像头对着收银台，不对着门。',
          vague: '你只能看见柜台后面有个人影。',
          misleading: '就一个店员，后面没人。这种店从来只排一个班。',
          nerveHint: '……"从来"这个词，你是从谁那儿听来的。',
        },
        abortHeat: 0,
        abortText: '你在门口停了一下，然后继续往前走了。',
        options: [
          {
            id: 'casual',
            label: '像个买烟的客人走进去',
            hint: '进得自然，出手要等',
            skill: 'nerve',
            defense: 'exposure',
            modifier: 0.1,
            onSuccess: [{ var: 'time', amount: 2 }],
            onFailure: [{ var: 'noise', amount: 16 }],
            successText: '他抬头看了你一眼，又低头去看电视了。',
            failureText: '他抬头看了你一眼，然后又看了一眼。',
          },
          {
            id: 'mask',
            label: '戴上东西再进',
            hint: '脸保住了，但一进门就摊牌',
            skill: 'nerve',
            defense: 'exposure',
            modifier: 0.04,
            onSuccess: [{ var: 'noise', amount: 12 }],
            onFailure: [{ var: 'noise', amount: 24 }],
            successText: '门铃响的时候他还没抬头。等他抬头，已经晚了。',
            failureText: '他在你推门的那一刻就按下了柜台下面的东西。',
          },
          {
            id: 'wait',
            label: '等他去后面理货',
            hint: '最安全，但要等',
            skill: 'stealth',
            defense: 'exposure',
            modifier: 0.14,
            onSuccess: [{ var: 'time', amount: 5 }],
            onFailure: [
              { var: 'time', amount: 5 },
              { var: 'noise', amount: 14 },
            ],
            successText: '他终于起身，往后面的库房走了。',
            failureText: '你在车里坐了半小时。一辆巡逻车从加油站门口开过。',
          },
        ],
      },
      {
        id: 'control',
        title: '控制',
        intro: '柜台，你，和一个不知道会怎么反应的人。',
        tell: {
          accurate: '他手边没有东西。警报按钮在收银机右侧，他够不着。',
          vague: '你不知道他手边有什么。',
          misleading: '这种店都没装警报。他手边什么都没有。',
          nerveHint: '……说这话的人，多半没在柜台后面站过。',
        },
        abortHeat: 20,
        abortText: '你把手从口袋里拿出来——空的——转身出了门。',
        options: [
          {
            id: 'quiet',
            label: '压低声音，让他自己打开',
            hint: '不惊动别人',
            skill: 'nerve',
            defense: 'security',
            modifier: 0.08,
            onSuccess: [
              { var: 'take', amount: 900 },
              { var: 'time', amount: 2 },
            ],
            onFailure: [{ var: 'noise', amount: 30 }],
            successText: '他的手在抖，但他照做了。整个过程没有人喊过一声。',
            failureText: '他愣住了，然后开始喊。喊得比你想的响。',
          },
          {
            id: 'loud',
            label: '吼他',
            hint: '快，但整条街都听见了',
            skill: 'nerve',
            defense: 'security',
            modifier: 0.18,
            onSuccess: [
              { var: 'take', amount: 1200 },
              { var: 'noise', amount: 26 },
            ],
            onFailure: [{ var: 'noise', amount: 40 }],
            successText: '他一句话都没说，把抽屉整个端出来放在柜台上。',
            failureText: '他一边把手举起来，一边用膝盖顶了柜台下面一下。',
          },
          {
            id: 'safe',
            label: '让他开保险柜',
            hint: '钱多得多，但要多待两分钟',
            skill: 'nerve',
            defense: 'security',
            modifier: -0.12,
            onSuccess: [
              { var: 'take', amount: 2200 },
              { var: 'time', amount: 5 },
              { var: 'noise', amount: 16 },
            ],
            onFailure: [
              { var: 'time', amount: 5 },
              { var: 'noise', amount: 34 },
            ],
            successText: '"延时锁，两分钟。" 他说这话的时候比你还紧张。',
            failureText: '"我没有钥匙。" 他说的可能是真的，但你已经耗掉了两分钟。',
          },
        ],
      },
      {
        id: 'leave',
        title: '撤离',
        intro: '门在身后关上。从这一刻起，有人在描述你的样子。',
        tell: {
          accurate: '车停在加油站侧面的暗处，从店里的窗户看不见。',
          vague: '你不确定有没有人看清你上了哪辆车。',
          misleading: '这个点路上不会有车。开出去两个路口就安全了。',
          nerveHint: '……你是怎么知道路上不会有车的。',
        },
        abortHeat: 24,
        abortText: '你把钱扔在地上，空着手跑了。',
        options: [
          {
            id: 'calm',
            label: '按限速开走',
            hint: '不引人注意',
            skill: 'nerve',
            defense: 'response',
            modifier: 0.06,
            onSuccess: [{ var: 'time', amount: 2 }],
            onFailure: [{ var: 'noise', amount: 14 }],
            successText: '你在第一个路口等了红灯。手在方向盘上，稳得不像刚才那个人。',
            failureText: '一辆巡逻车从对面过来，慢了下来。',
          },
          {
            id: 'floor',
            label: '踩到底',
            hint: '最快，也最响',
            skill: 'driving',
            defense: 'response',
            modifier: 0,
            onSuccess: [{ var: 'noise', amount: 18 }],
            onFailure: [{ var: 'noise', amount: 32 }],
            successText: '三个街区，一次都没减速。',
            failureText: '轮胎在路口打滑。有人拿手机对着你的车牌。',
          },
          {
            id: 'ditch',
            label: '把车丢了，走着回去',
            hint: '最保险，但你少一辆车',
            skill: 'stealth',
            defense: 'response',
            modifier: 0.16,
            onSuccess: [{ var: 'time', amount: 6 }],
            onFailure: [{ var: 'noise', amount: 20 }],
            successText: '车停在两公里外的巷子里。你走回去，走了四十分钟。',
            failureText: '你下车的时候，对面楼上有一扇窗是亮的。',
          },
        ],
      },
    ],
  },
}

export const crimeConfig = (key: CrimeKey): SegmentRunConfig => CRIME_CONFIGS[key]

export const CRIME_LABELS: Record<CrimeKey, string> = {
  pickpocket: '扒窃',
  atm: '撬取款机',
  burgle: '入室行窃',
  holdup: '持械抢劫',
}

/** §3.3 — 持械抢劫会让人记住你的脸，那一段进底案，贿赂消不掉。 */
export const LEAVES_A_FACE: Record<CrimeKey, number> = {
  pickpocket: 0,
  atm: 0,
  burgle: 0,
  holdup: 10,
}

/** 行动点消耗。扒窃最便宜，入室最贵。 */
export const CRIME_AP: Record<CrimeKey, number> = {
  pickpocket: 1,
  atm: 2,
  burgle: 2,
  holdup: 2,
}
